#include "gui/FtusLookAndFeel.h"

#include "FtusAssets.h" // generated by the ftus_assets binary-data target (fonts GLOBbed)

namespace ftus {

namespace {

juce::Typeface::Ptr loadEmbeddedTypeface(const char* data, int size) {
    if (data == nullptr || size <= 0)
        return nullptr;
    return juce::Typeface::createSystemTypefaceFor(data, static_cast<size_t>(size));
}

} // namespace

juce::Typeface::Ptr FtusLookAndFeel::regularTypeface() {
    static juce::Typeface::Ptr tf =
        loadEmbeddedTypeface(FtusAssets::InterRegular_ttf, FtusAssets::InterRegular_ttfSize);
    return tf;
}

juce::Typeface::Ptr FtusLookAndFeel::mediumTypeface() {
    static juce::Typeface::Ptr tf =
        loadEmbeddedTypeface(FtusAssets::InterMedium_ttf, FtusAssets::InterMedium_ttfSize);
    return tf;
}

juce::Font FtusLookAndFeel::font(float height, bool medium) {
    if (auto tf = medium ? mediumTypeface() : regularTypeface())
        return juce::Font(juce::FontOptions(tf).withHeight(height));
    return juce::Font(juce::FontOptions().withHeight(height)); // system fallback
}

FtusLookAndFeel::FtusLookAndFeel()
    : juce::LookAndFeel_V4({theme::bg, theme::panel, theme::panelRaised, theme::stroke,
                            theme::text, theme::accent, juce::Colours::white, theme::accent,
                            theme::text}) {
    setColour(juce::ResizableWindow::backgroundColourId, theme::bg);
    setColour(juce::DocumentWindow::textColourId, theme::text);

    setColour(juce::TextButton::buttonColourId, theme::control);
    setColour(juce::TextButton::buttonOnColourId, theme::accent);
    setColour(juce::TextButton::textColourOffId, theme::text);
    setColour(juce::TextButton::textColourOnId, theme::bg);

    setColour(juce::ComboBox::backgroundColourId, theme::control);
    setColour(juce::ComboBox::outlineColourId, theme::stroke);
    setColour(juce::ComboBox::textColourId, theme::text);
    setColour(juce::ComboBox::arrowColourId, theme::textDim);
    setColour(juce::ComboBox::buttonColourId, theme::control);

    setColour(juce::PopupMenu::backgroundColourId, theme::panelRaised);
    setColour(juce::PopupMenu::textColourId, theme::text);
    setColour(juce::PopupMenu::headerTextColourId, theme::textDim);
    setColour(juce::PopupMenu::highlightedBackgroundColourId, theme::accent.withAlpha(0.18f));
    setColour(juce::PopupMenu::highlightedTextColourId, juce::Colours::white);

    setColour(juce::Slider::rotarySliderFillColourId, theme::accent);
    setColour(juce::Slider::rotarySliderOutlineColourId, theme::stroke);
    setColour(juce::Slider::thumbColourId, theme::text);
    setColour(juce::Slider::trackColourId, theme::accent);
    setColour(juce::Slider::backgroundColourId, theme::control);

    setColour(juce::Label::textColourId, theme::text);

    setColour(juce::AlertWindow::backgroundColourId, theme::panelRaised);
    setColour(juce::AlertWindow::textColourId, theme::text);
    setColour(juce::AlertWindow::outlineColourId, theme::stroke);

    setColour(juce::TextEditor::backgroundColourId, theme::bg);
    setColour(juce::TextEditor::textColourId, theme::text);
    setColour(juce::TextEditor::outlineColourId, theme::stroke);
    setColour(juce::TextEditor::focusedOutlineColourId, theme::accent);
    setColour(juce::TextEditor::highlightColourId, theme::accent.withAlpha(0.35f));
    setColour(juce::CaretComponent::caretColourId, theme::accent);

    setColour(juce::TooltipWindow::backgroundColourId, theme::panelRaised);
    setColour(juce::TooltipWindow::textColourId, theme::text);
    setColour(juce::TooltipWindow::outlineColourId, theme::stroke);

    setColour(juce::ScrollBar::thumbColourId, theme::stroke);
    setColour(juce::ListBox::backgroundColourId, theme::panel);
}

void FtusLookAndFeel::drawRotarySlider(juce::Graphics& g, int x, int y, int width, int height,
                                       float sliderPos, float rotaryStartAngle,
                                       float rotaryEndAngle, juce::Slider& slider) {
    const auto bounds = juce::Rectangle<float>(static_cast<float>(x), static_cast<float>(y),
                                               static_cast<float>(width),
                                               static_cast<float>(height));
    const float radius = juce::jmin(bounds.getWidth(), bounds.getHeight()) * 0.5f - 3.0f;
    if (radius < 6.0f)
        return;
    const float cx = bounds.getCentreX();
    const float cy = bounds.getCentreY();
    const float alpha = slider.isEnabled() ? 1.0f : 0.4f;
    const bool bipolar = static_cast<bool>(slider.getProperties()["ftusBipolar"]);
    const float thickness = juce::jmax(2.4f, radius * 0.11f);
    const float arcR = radius - thickness * 0.5f;
    const float angle = rotaryStartAngle + sliderPos * (rotaryEndAngle - rotaryStartAngle);
    const float midAngle = (rotaryStartAngle + rotaryEndAngle) * 0.5f; // 12 o'clock

    // Track arc.
    juce::Path track;
    track.addCentredArc(cx, cy, arcR, arcR, 0.0f, rotaryStartAngle, rotaryEndAngle, true);
    g.setColour(theme::stroke.withMultipliedAlpha(alpha));
    g.strokePath(track, juce::PathStrokeType(thickness, juce::PathStrokeType::curved,
                                             juce::PathStrokeType::rounded));

    // Value arc: from the start (unipolar) or from 12 o'clock (bipolar).
    const float from = bipolar ? juce::jmin(midAngle, angle) : rotaryStartAngle;
    const float to = bipolar ? juce::jmax(midAngle, angle) : angle;
    if (to - from > 0.012f) {
        juce::Path value;
        value.addCentredArc(cx, cy, arcR, arcR, 0.0f, from, to, true);
        g.setColour(theme::accent.withMultipliedAlpha(alpha));
        g.strokePath(value, juce::PathStrokeType(thickness, juce::PathStrokeType::curved,
                                                 juce::PathStrokeType::rounded));
    }

    // Center notch for bipolar knobs.
    if (bipolar) {
        juce::Path notch;
        notch.startNewSubPath(cx + std::sin(midAngle) * (arcR - thickness * 0.9f),
                              cy - std::cos(midAngle) * (arcR - thickness * 0.9f));
        notch.lineTo(cx + std::sin(midAngle) * (arcR + thickness * 0.9f),
                     cy - std::cos(midAngle) * (arcR + thickness * 0.9f));
        g.setColour(theme::textDim.withMultipliedAlpha(0.9f * alpha));
        g.strokePath(notch, juce::PathStrokeType(1.4f));
    }

    // Knob body.
    const float bodyR = arcR - thickness * 0.5f - 2.5f;
    g.setColour(theme::control.withMultipliedAlpha(alpha));
    g.fillEllipse(cx - bodyR, cy - bodyR, bodyR * 2.0f, bodyR * 2.0f);
    g.setColour(theme::stroke.withMultipliedAlpha(alpha));
    g.drawEllipse(cx - bodyR, cy - bodyR, bodyR * 2.0f, bodyR * 2.0f, 1.0f);

    // Pointer.
    juce::Path pointer;
    pointer.startNewSubPath(cx + std::sin(angle) * bodyR * 0.42f,
                            cy - std::cos(angle) * bodyR * 0.42f);
    pointer.lineTo(cx + std::sin(angle) * bodyR * 0.88f, cy - std::cos(angle) * bodyR * 0.88f);
    g.setColour(theme::text.withMultipliedAlpha(alpha));
    g.strokePath(pointer, juce::PathStrokeType(juce::jmax(2.0f, radius * 0.07f),
                                               juce::PathStrokeType::curved,
                                               juce::PathStrokeType::rounded));
}

void FtusLookAndFeel::drawButtonBackground(juce::Graphics& g, juce::Button& button,
                                           const juce::Colour& backgroundColour,
                                           bool highlighted, bool down) {
    auto bounds = button.getLocalBounds().toFloat().reduced(0.5f);
    auto base = backgroundColour;
    if (down)
        base = base.darker(0.25f);
    else if (highlighted)
        base = base.brighter(0.10f);
    g.setColour(base);
    g.fillRoundedRectangle(bounds, 4.0f);
    g.setColour(theme::stroke);
    g.drawRoundedRectangle(bounds, 4.0f, 1.0f);
}

void FtusLookAndFeel::drawToggleButton(juce::Graphics& g, juce::ToggleButton& button,
                                       bool highlighted, bool down) {
    const bool on = button.getToggleState();
    auto bounds = button.getLocalBounds().toFloat().reduced(0.5f);
    auto bg = on ? theme::accent : theme::control;
    if (down)
        bg = bg.darker(0.2f);
    else if (highlighted)
        bg = bg.brighter(0.08f);
    g.setColour(bg);
    g.fillRoundedRectangle(bounds, 4.0f);
    g.setColour(on ? theme::accent.darker(0.15f) : theme::stroke);
    g.drawRoundedRectangle(bounds, 4.0f, 1.0f);
    g.setColour(on ? theme::bg : theme::textDim);
    g.setFont(font(10.0f, true));
    g.drawText(button.getButtonText(), bounds, juce::Justification::centred, false);
}

juce::Font FtusLookAndFeel::getTextButtonFont(juce::TextButton&, int buttonHeight) {
    return font(juce::jmin(12.0f, static_cast<float>(buttonHeight) * 0.65f), true);
}
juce::Font FtusLookAndFeel::getComboBoxFont(juce::ComboBox&) { return font(12.0f); }
juce::Font FtusLookAndFeel::getPopupMenuFont() { return font(13.0f); }
juce::Font FtusLookAndFeel::getLabelFont(juce::Label& label) {
    return font(label.getFont().getHeight());
}
juce::Font FtusLookAndFeel::getAlertWindowTitleFont() { return font(16.0f, true); }
juce::Font FtusLookAndFeel::getAlertWindowMessageFont() { return font(13.5f); }
juce::Font FtusLookAndFeel::getAlertWindowFont() { return font(13.0f); }

juce::Rectangle<int> FtusLookAndFeel::getTooltipBounds(const juce::String& tipText,
                                                       juce::Point<int> screenPos,
                                                       juce::Rectangle<int> parentArea) {
    const auto f = font(12.0f);
    const int w = juce::jmin(320, juce::roundToInt(juce::GlyphArrangement::getStringWidth(f, tipText)) + 18);
    const int h = 22;
    return juce::Rectangle<int>(screenPos.x > parentArea.getCentreX() ? screenPos.x - (w + 12)
                                                                      : screenPos.x + 18,
                                screenPos.y > parentArea.getCentreY() ? screenPos.y - (h + 6)
                                                                      : screenPos.y + 12,
                                w, h)
        .constrainedWithin(parentArea);
}

void FtusLookAndFeel::drawTooltip(juce::Graphics& g, const juce::String& text, int width,
                                  int height) {
    const auto r = juce::Rectangle<float>(0, 0, static_cast<float>(width),
                                          static_cast<float>(height));
    g.setColour(theme::panelRaised);
    g.fillRoundedRectangle(r, 4.0f);
    g.setColour(theme::stroke);
    g.drawRoundedRectangle(r.reduced(0.5f), 4.0f, 1.0f);
    g.setColour(theme::text);
    g.setFont(font(12.0f));
    g.drawText(text, r.reduced(8.0f, 2.0f), juce::Justification::centredLeft, true);
}

} // namespace ftus
